<h1 style="font-family:Patua One;text-align:center;font-size=45px;color:#049AE1;">Machine Learning Laboratory </h1>
<h2 style="font-family:Patua One;text-align:center;font-size=45px;color:#049AE1;">(410302) </h2>
<h3 style="font-family:Bookman Old Style;text-align:center;font-size=35px;color:#03D1EE;">BE Sem I Honors in AI/ML </h3>
<h4 style="font-family:Bookman Old Style;text-align:center;font-size=30px;color:#03D1EE;">Academic Year: 2022-23 </h4>
<h2 style="font-family:Farro;text-align:center;font-size=50px;color:#02DA87;">Lab Assignment No.1  </h2>
<h4 style="font-family:Bookman Old Style;text-align:right;font-size=30px;color:#A6065B;">Name - XYZ </h4>
<h4 style="font-family:Bookman Old Style;text-align:right;font-size=30px;color:#A6065B;">Roll No. - 12345 </h4>
<h4 style="font-family:Bookman Old Style;text-align:right;font-size=30px;color:#A6065B;">Branch - E&TE </h4>
<h4 style="font-family:Bookman Old Style;text-align:right;font-size=30px;color:#A6065B;">College - P.I.C.T </h4>
<br>

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;"> 1. Import NumPy as np </p>


In [1]:
import numpy as np

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">2. Create an array of 10 zeros. </p>


In [2]:
# CODE HERE

Array_of_Zeros = np.zeros((10, ), dtype=int) 

print("An array of ten \'0\'s: ", Array_of_Zeros)

An array of ten '0's:  [0 0 0 0 0 0 0 0 0 0]


In [2]:
# DON'T WRITE HERE

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">3. Create an array of 10 ones.</p>


In [3]:
Array_of_Ones=np.ones((10, ), dtype=int) 

print("An array of ten \'1\'s: ",Array_of_Ones)

An array of ten '1's:  [1 1 1 1 1 1 1 1 1 1]


In [3]:
# DON'T WRITE HERE

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">4. Create an array of 10 fives.</p>


In [4]:
Array_of_Fives=np.ones((10, ), dtype=int)*5

print("An array of ten \'5\'s: ",Array_of_Fives)

An array of ten '5's:  [5 5 5 5 5 5 5 5 5 5]


In [4]:
# DON'T WRITE HERE

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">5. Create an array of the integers from 10 to 50.</p>


In [5]:
#Here I have used "arange()" function of numpy

Array_10_50=np.arange(10,51)

print("An array of integers from \'10\' to \'50\': ",Array_10_50)


An array of integers from '10' to '50':  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [5]:
# DON'T WRITE HERE

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">6. Create an array of all the even integers from 10 to 50.</p>

In [6]:
Array_10_50_Even=np.array([i for i in range(10,51) if i%2==0])

print("An array of even integers from \'10\' to \'50\': ",Array_10_50_Even)


An array of even integers from '10' to '50':  [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [6]:
# DON'T WRITE HERE

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">7. Create a 3x3 matrix with values ranging from 0 to 8.</p>

In [10]:
# Here I have used "arange()" & "reshape()" functions of numpy

My_arr=np.arange(9).reshape(3, 3)

print("***** The 3 x 3 Matrix is as follows *****")

print(My_arr)


***** The 3 x 3 Matrix is as follows *****
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# DON'T WRITE HERE

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">8. Create a 3x3 identity matrix.</p>


In [11]:

Identity_Matrix = np.identity(3, dtype=int)

print("***** 3x3 Identity Matrix *****")

print(Identity_Matrix)


***** 3x3 Identity Matrix *****
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [8]:
# DON'T WRITE HERE

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">9. Use NumPy to generate a random number between 0 and 1.
<br>NOTE: Your result's value should be different from the one shown below.
</p>


In [12]:
from numpy import random

Rand_Num = random.rand()

print("Any Random Number between 0 and 1: ",Rand_Num)


Any Random Number between 0 and 1:  0.0066052635743106825


In [9]:
# DON'T WRITE HERE

array([0.65248055])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution.
<br>NOTE: Your result's values should be different from the ones shown below.
</p>

In [13]:

# I have given the mean as '1' and standard deviation as '0.5' for random.normal() function

Normal_Distribution = np.random.normal(1,0.5,25)

print(Normal_Distribution)


[ 0.40552509  1.65203935  1.56788369  0.62905264  1.00144584  1.09168873
  1.38847372  1.29816108  0.63518679  1.16410044  0.81306757  1.4050996
  0.61999595  0.95118654  0.75883491  1.14770683  0.3962428   2.2355631
  1.74264371 -0.07794645  1.40535089  1.6631632   1.49595928  1.05728346
 -0.14027249]


In [10]:
# DON'T WRITE HERE

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">11. Create the following matrix:
</p>

In [14]:

# I used step value as 0.01 in arange() function

My_mat=np.arange(0.01,1.01,0.01).reshape(10,10)

print(My_mat)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [11]:
# DON'T WRITE HERE

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">12. Create an array of 20 linearly spaced points between 0 and 1:
</p>

In [15]:
# I have used linspace() function of NumPy here

Linespace_Mat = np.linspace(0, 1, 20)

print(Linespace_Mat)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [12]:
# DON'T WRITE HERE

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [16]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">13. Write code that reproduces the output shown below.<br>Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.
</p>


In [17]:
# CODE HERE

# used slicing in Matrices here

New_Mat=mat[2:,1:]

print(New_Mat)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [14]:
# DON'T WRITE HERE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">14. Write code that reproduces the output shown below. 
</p>


In [18]:

# Identified the required element using indexing in matrix

Element_in_Mat=mat[3,4]

print(Element_in_Mat)

20


In [15]:
# DON'T WRITE HERE

20

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">15. Write code that reproduces the output shown below.
</p>


In [19]:
# Fetched the first three elements in the second column of maxtrix as per required problem

Elements_in_second_Column=mat[0:3,1].reshape(3,1)

print(Elements_in_second_Column)


[[ 2]
 [ 7]
 [12]]


In [16]:
# DON'T WRITE HERE

array([[ 2],
       [ 7],
       [12]])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">16. Write code that reproduces the output shown below.
</p>


In [20]:

# Fetched the all elements from last row of matrix

Elements_in_last_row=mat[4,:]

print(Elements_in_last_row)

[21 22 23 24 25]


In [17]:
# DON'T WRITE HERE

array([21, 22, 23, 24, 25])

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">17. Write code that reproduces the output shown below.
</p>



In [21]:

#Fetching elements in last two rows of given matrix

New_M=mat[3:,:]

print(New_M)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
# DON'T WRITE HERE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">18. Get the sum of all the values in mat.
</p>



In [22]:
# Using sum() function to get total of all elements in matrix

print("Sum of all elements in matrix: ",mat.sum())

Sum of all elements in matrix:  325


In [19]:
# DON'T WRITE HERE

325

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">19. Get the standard deviation of the values in mat.
</p>



In [23]:
# Using sts() function to compute standard deviation of all elements in matrix

print("Standard deviation of all elements in matrix: ",mat.std())


Standard deviation of all elements in matrix:  7.211102550927978


In [20]:
# DON'T WRITE HERE

7.211102550927978

<br><p style="font-family:Footlight MT Light;text-align:left;font-size:1.2em;font-weight:bold;color:#D90571;">20. Get the sum of all the columns in mat.
</p>

In [24]:
# Using 'axis' attribute of sum() function to get total of all elements in matrix columnwise

Columnwise_Sum_matrix= mat.sum(axis=0)

print("Sum of all elements in matrix columnwise: ",Columnwise_Sum_matrix)


Sum of all elements in matrix columnwise:  [55 60 65 70 75]


In [21]:
# DON'T WRITE HERE

array([55, 60, 65, 70, 75])

# Great Job!